plugins:
  babble_enabled:
    default: true
    client: true
  babble_placeholder:
    default: ""
    client: true
  babble_icon:
    default: "bullhorn"
    client: true
  babble_max_topic_size:
    default: 200
  babble_category_name:
    default: chat
  babble_remote_post:
    default: false
  babble_remote_url:
    default: http://example.com/api/message/add
